/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;
//Importa a classe LocalDate do pacote java.time, ela é usada para trabalhar com datas
import java.time.LocalDate;
/**
 *
 * @author Raika
 */
public class Calculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora.class.getName());

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        bntCalcula = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 63, 80, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 63, -1, -1));

        lblData.setText("Ano de Nascimento");
        getContentPane().add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 66, -1, -1));

        bntCalcula.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raika\\Downloads\\calculator (1).png")); // NOI18N
        bntCalcula.setText("Calcular");
        bntCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalculaActionPerformed(evt);
            }
        });
        getContentPane().add(bntCalcula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        lblResultado.setText("0 anos");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raika\\Downloads\\age-group (1).png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 70, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalculaActionPerformed
     //Pega o ano de nascimento (string) e converte para inteiro
        int anoNascimento = Integer.parseInt(txtNascimento.getText());
        //LocalDate.now() cria um objeto LocalDate com a data atual do sistema
        //getYear() pega apenas o ano desse objeto
        int anoAtual = LocalDate.now().getYear();
        //calcula a idade
        int idade = anoAtual - anoNascimento;
        //modifica o resultado, mostrando a idade atual
        lblResultado.setText(idade + "anos");
    }//GEN-LAST:event_bntCalculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCalcula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtNascimento;
    // End of variables declaration//GEN-END:variables
}
