/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author Raika
 */
public class Gênio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gênio.class.getName());

    /**
     * Creates new form Gênio
     */
    public Gênio() {
        initComponents();
        configurarSpinner();
        
        //mostra o texto inicial com quebra de linha
        lblTexto.setText("<html>Bem-Vindo ao Jogo da Advinhação!<br>Escolha um número de 1 a 5.<html>");
    }
    
    //função para configurar o spinner
    private void configurarSpinner(){
        //configura o spinner com o número inicial, minímo, máximo e passo (nessa ordem)
        javax.swing.SpinnerNumberModel model = new javax.swing.SpinnerNumberModel(0, 0, 5, 1);
        //atribui as configurações para o spinner já criado
        spnNumero.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spnNumero = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        lblTexto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Escolha um valor: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(spnNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 193, 80, 30));

        lblTexto.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblTexto.setText("As instruções aparecerão aqui!!");
        getContentPane().add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 260, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raika\\Downloads\\akinator__1_-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 140, 120));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raika\\Downloads\\fala__1___1_-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        //faz um cast direto para Integer, transformando o valor do spinner em int com o método getValue()
        int palpite = (Integer) spnNumero.getValue();
        int numero = (int) (Math.random() * 5) + 1; //define os valores aleatórios
        
        //condição para saber se acertou o número ou não
        if (palpite == numero)
            lblTexto.setText("ACERTOU!!");
        else 
            lblTexto.setText("ERROU!! Eu pensei no valor " +numero);
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gênio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JSpinner spnNumero;
    // End of variables declaration//GEN-END:variables
}
