/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Raika
 */
public class Repetição extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Repetição.class.getName());

    /**
     * Creates new form Repetição
     */
    public Repetição() {
        initComponents();
        //Configura para começar no valor 1
        sldPasso.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInicio = new javax.swing.JLabel();
        lblFim = new javax.swing.JLabel();
        lblPasso = new javax.swing.JLabel();
        sldInicio = new javax.swing.JSlider();
        sldFim = new javax.swing.JSlider();
        sldPasso = new javax.swing.JSlider();
        lblNum1 = new javax.swing.JLabel();
        lblNum2 = new javax.swing.JLabel();
        lblNum3 = new javax.swing.JLabel();
        btnContar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblInicio.setText("Início");
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 51, -1, -1));

        lblFim.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblFim.setText("Fim");
        getContentPane().add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblPasso.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblPasso.setText("Passo");
        getContentPane().add(lblPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        sldInicio.setValue(0);
        sldInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldInicioStateChanged(evt);
            }
        });
        getContentPane().add(sldInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        sldFim.setValue(0);
        sldFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFimStateChanged(evt);
            }
        });
        getContentPane().add(sldFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        sldPasso.setMaximum(10);
        sldPasso.setMinimum(1);
        sldPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPassoStateChanged(evt);
            }
        });
        getContentPane().add(sldPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        lblNum1.setText("0");
        getContentPane().add(lblNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 30, -1));

        lblNum2.setText("0");
        getContentPane().add(lblNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 30, -1));

        lblNum3.setText("1");
        getContentPane().add(lblNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 20, -1));

        btnContar.setText("Contar");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        txtAreaResultado.setColumns(20);
        txtAreaResultado.setRows(5);
        jScrollPane1.setViewportView(txtAreaResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 150, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldInicioStateChanged
        //pega o valor do slider
        int valorAtual = sldInicio.getValue();
        //atualiza a label
        //String.valueOf() transforma o inteiro em string para ir para a label
        lblNum1.setText(String.valueOf(valorAtual));
    }//GEN-LAST:event_sldInicioStateChanged

    private void sldFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFimStateChanged
        //paga o valor do slider 
        int valorAtual = sldFim.getValue();
        //atualiza o label
        lblNum2.setText(String.valueOf(valorAtual));
    }//GEN-LAST:event_sldFimStateChanged

    private void sldPassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPassoStateChanged
        //pega o valor do slider
        int valorAtual = sldPasso.getValue();
        //atualiza a label
        lblNum3.setText(String.valueOf(valorAtual));
    }//GEN-LAST:event_sldPassoStateChanged

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        //utilizei o try/catch para identificar exceções 
        try {
            int inicio = sldInicio.getValue();
            int fim = sldFim.getValue();
            int passo = sldPasso.getValue();
            //caso o fim seja menor que o inicio
            if (fim < inicio){
                //exibe uma mensagem de erro ao usuário
                JOptionPane.showMessageDialog (this, 
                "Erro: O valor final NÃO pode ser maior que o inicial!", "Erro de validação", 
                JOptionPane.ERROR_MESSAGE);
                return;
            }
        
            //StringBuilder constrói a string de resultado
            StringBuilder resultado = new StringBuilder();
        
            for (int i = inicio; i <= fim; i += passo){
                //adiciona cada número da sequência seguido de quebra de texto 
                resultado.append(i).append("\n");
            }
            //mostra a sequencia na área de texto
            txtAreaResultado.setText(resultado.toString());
        } catch (Exception e) {
            // o catch captura as exceções não previstas anteriormente
            //exibe a mensagem de erro ao usuário
            JOptionPane.showMessageDialog (this, "Erro inesperado: " + e.getMessage(), "Erro", 
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnContarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Repetição().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum2;
    private javax.swing.JLabel lblNum3;
    private javax.swing.JLabel lblPasso;
    private javax.swing.JSlider sldFim;
    private javax.swing.JSlider sldInicio;
    private javax.swing.JSlider sldPasso;
    private javax.swing.JTextArea txtAreaResultado;
    // End of variables declaration//GEN-END:variables
}
